apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: atcoder-scheduler-daemonset
  labels:
    app: atcoder-scheduler
spec:
  selector:
    matchLabels:
      app: atcoder-scheduler
  template:
    metadata:
      labels:
        app: atcoder-scheduler
    spec:
      containers:
        - name: atcoder-scheduler
          image: itta/atcoder-scheduler:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
